[nfs]
172.31.34.73 ansible_ssh_user='ec2-user'

[webservers]
172.31.32.252 ansible_ssh_user='ec2-user'
172.31.36.92 ansible_ssh_user='ec2-user'

[db]
172.31.44.110 ansible_ssh_user='ubuntu' 

[lb]
172.31.6.218 ansible_ssh_user='ubuntu'