---
- name: Include dynamic variables 
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Include common file 
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: uat webservers
  import_playbook: ../static-assignments/uat-webservers.yml

- name: import database file
  import_playbook: ../static-assignments/db.yml

- name: loadbalancer
  import_playbook: ../static-assignments/load-balancers.yml
  when: load_balancer_is_required
